### ISSUE TITLE
How to quote SQLite identifiers

### ISSUE THREAD

**Issue by shofetim** [janet-lang/sqlite3#18]
Test case:

Running this:
```
(import sqlite3 :as sql)
(def db (sql/open "test.db"))
(sql/eval db `CREATE TABLE customers (id INTEGER PRIMARY KEY, "first-name" TEXT);`)
(sql/eval db `INSERT INTO customers (id, "first-name") VALUES(:id, :first-name);`
          {:first-name "John" :id 12345})
```

Results in:
```
error: no such column: name
  in sqlite3/eval
  in _thunk [test.janet] (tailcall) on line 4, column 1
```

It should be possible to quote SQLite identifiers with any of "" `` [] for reference see: https://www.sqlite.org/lang_keywords.html

None of which appear to work.

Opening the same DB in the SQLite command line client and executing
`INSERT INTO customers (id, "first-name") VALUES(12345, 'John');`

Works as expected.

**Comment by strangepete** [comment]
This seems to be normal; parameters are specified only as being alphanumeric. If you manually set the same named parameters in sqlite repl, it will happily store the colonized-keyword, but will error the same as above when executing the insert. And you can't quote the keyword within VALUES or its interpreted as just a string to save. Double quotes are just fine for the actual column name.

```
sqlite> .parameter set :id 123
sqlite> .parameter set :first-name "pete"
sqlite> INSERT INTO customers (id, "first-name") VALUES(:id, :first-name);
Error: in prepare, no such column: name (1)
```

The sqlite documentation isn't super specific on the format, but I came across someone else as well [with the same issue on SO](https://stackoverflow.com/questions/28194005/python-sqlite-named-parameter-containing-dash) with the conclusion that the '-' is likely being taken as a minus sign.

**Comment by shofetim** [comment]
Per SQLite's [docs](https://www.sqlite.org/c3ref/bind_blob.html) it does appear that the parameters names must be alphanumeric, and cannot be escaped.
