### ISSUE TITLE
Option to link system sqlite3 library

### ISSUE THREAD

**Issue by andrewchambers** [janet-lang/sqlite3#4]
```
https://www.sqlite.org/howtocorrupt.html
```
```
2.2.1. Multiple copies of SQLite linked into the same application

As pointed out in the previous paragraph, SQLite takes steps to work around the quirks of POSIX advisory locking. Part of that work-around involves keeping a global list (mutex protected) of open SQLite database files. But, if multiple copies of SQLite are linked into the same application, then there will be multiple instances of this global list. Database connections opened using one copy of the SQLite library will be unaware of database connections opened using the other copy, and will be unable to work around the POSIX advisory locking quirks. A close() operation on one connection might unknowingly clear the locks on a different database connection, leading to database corruption.

The scenario above sounds far-fetched. But the SQLite developers are aware of at least one commercial product that was released with exactly this bug. The vendor came to the SQLite developers seeking help in tracking down some infrequent database corruption issues they were seeing on Linux and Mac. The problem was eventually traced to the fact that the application was linking against two separate copies of SQLite. The solution was to change the application build procedures to link against just one copy of SQLite instead of two.
```

It's somewhat of a ticking time bomb if someone is making a hybrid C/Janet application and wants to use sqlite3 from C code.

I think we should at the very least default to trying the system lib unless the user specifically requests the builtin library.

**Comment by bakpakin** [comment]
It may be desirable to have the option to link to the system library, but I don't want to do that by default.

Perhaps we need some mechanism for specifying configurations for dependencies, and an option to pass install flags to deps - this would also of course need to be added to lockfiles

**Comment by oz123** [comment]
Maybe this can be solved by adding a custom rule? Instead of build having a "build-sys" or so?

**Comment by bakpakin** [comment]
Any sort of configuration would probably be easiest to do as either an environment variable or as a flag to jpm. It would really just involve wrapping `declare-native` in project.janet with some conditional.


```
(if use-system-lib
  (declare-native
    :name sqlite3
    :source @["main.c"]
    :ldflags @["-lsqlite"]))
  (declare-native
    :name "sqlite3"
    :source @["sqlite3.c" "main.c"]))
```

Or perhaps use pkg-config or similar.

**Comment by oz123** [comment]
I will prepare a PR. I like this approach.

Just out of curiosity, can project.janet provide a custom build command to extend and override the default build command?

**Comment by sogaiu** [comment]
@oz123 IIUC, here is an example of one way: https://gitlab.com/sogaiu/judge-gen/-/blob/master/project.janet#L8-11

**Comment by oz123** [comment]
interesting. That is simply overriding the rule. 
And for extended rule there is the possibility of adding a dependent rule.
Thanks for the heads up 😊

**Comment by oz123** [comment]
@andrewchambers can the issue be closed?
Since #8 is merged.
Thinking out loud: maybe, your comment deserves a note in the README ?

**Comment by andrewchambers** [comment]
@oz123 yeah could be a good comment.
